---

# Delegate further configuration to subtasks
# placed in this same directory.

- include: install.yml
- include: configure.yml

- name: Ensure supervisord is running
  become: yes
  service:
    name: "{{supervisord_service_name}}"
    state: running
    enabled: yes
  tags:
    - init
    - supervisor
    - supervisord

- name: Force systemctl enable supervisor ( Bug in ubuntu 16.04 pkg )
  become: yes
  command: systemctl enable supervisor
  when: ansible_os_family == 'Debian'
  tags:
    - init
    - supervisor
    - supervisord

