---

- name: restart supervisord
  become: yes
  service: name=supervisor state=restarted
  when: ansible_service_mgr != '/sbin/launchd'

- name: launchd | restart supervisord
  become: yes
  shell: launchctl unload -w {{ supervisord_init_script }}; launchctl load -w {{ supervisord_init_script }}
  when: ansible_service_mgr == '/sbin/launchd'

- name: reread supervisord
  become: yes
  command: supervisorctl reread

- name: update supervisord
  become: yes
  command: supervisorctl update
